Class relationships
paulshaun-kdtk/School_Library pull request #4
Opened 2023-10-26 14:17 UTC by paulshaun-kdtk

# Changes

- modified person and student classes to link to rental and book classess
- created classroom, rental and book classes

2023-10-26 15:17 UTC, skyv26 requested changes
## Hi @paulshaun-kdtk, 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMjBkMDI3OWJlYzRhNWVlNmIyZmE5NjU5NzFlZTA0NDVjZWFhMmQ2NSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implemented the features ✅ 
- Professional `README` template ✅ 

## Required Changes ♻️

- [OPTIONAL] Please make sure that your `commit` messages should be meaningful, and tell something informative about your progress in the commit history as per the `general` requirements.

![image](https://github.com/paulshaun-kdtk/School_Library/assets/66476329/e23ba89c-4e0a-4740-ac35-9b3d3709ff54)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-26 15:17 UTC, skyv26 commented on classroom.rb
> +    student.classroom = self
- [ ] Good Job 👏🏻 , you did an awesome job, but I think you forgot to add the `@` symbol before the students to append the new student. Without it I am getting an error, because `students` is not defined, `` the **students** is a local variable whereas **@students** is an instance variable which is defined in the constructor.

2023-10-26 15:17 UTC, skyv26 commented on book.rb
- [ ] Well done **Shaun**, excellent work so far, but It seems like you forgot to add the `method` for adding the `rentals` because as per requirement you should establish the relation between `rentals` and `book` by keep in mind, you are establishing `has_many` relation of the book with rentals. So in short, you should implement which fulfil `book` has many rentals, at different times, a book can be taken by different people.

2023-10-27 11:58 UTC, zieeco requested changes
Hi @paulshaun-kdtk,

<img height="80" src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>



Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Great job adding some changes.✔️
- Nice code implementation ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions

 - N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-27 11:58 UTC, zieeco commented on book.rb
- As suggested by the previous reviewer, kindly add the rentals method to establish the has_many relationship. The method should look something like this.

```ruby
def add_rental(person, date)
    Rental.new(date, self, person)
 end
```

2023-10-27 20:09 UTC, cynthiainga approved these changes
## STATUS APPROVED ✔️ 🎉 🎉 

Hi @paulshaun-kdtk, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] All requested changes are made ✔️ 
- [ ] No linters errors ✔️ 
- [ ] Correct Gitflow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-28 14:22 UTC, merged